### ISSUE TITLE
Impossible to create a GET and a POST on a same url ?

### ISSUE THREAD

**Issue by douineauromain** [VGJohn/totoro#1]
Hello 

```
app.use('/', totoro.rain({
    1: {
        // COMMENTS
        deprecated: true,
        "/functions/getComments": {
            method: "POST",
            endpointImplementation: test
        },
        "/functions/setComment": {
            method: "POST",
            endpointImplementation: test
        }
    },
    2: {
        "/comments": {
            method: "GET",
            endpointImplementation: test
        },
        "/comments": {
            method: "POST",
            endpointImplementation: test
        }
    }
}));
```

It seems it impossible to do this, it will create only the V2 POST route 😢 

> debug: Adding routes for API version 1
debug: Adding route 'POST  /1/functions/getComments'
debug: Adding route 'POST  /1/functions/setComment'
debug:  
debug: Adding routes for API version 2
debug: Adding route 'POST  /2/comments'

**Comment by mohsinAnomaly** [comment]
It's not issue with totoro itself. If you read your code 2: {
        "/comments": {
            method: "GET",
            endpointImplementation: test
        },
        "/comments": {
            method: "POST",
            endpointImplementation: test
        }
    }
then as per javascript you are considering two objects in  attribute 2. But the key passed to the given two  attributes is same i.e. "/comments". So simply it will override the value of key "/comments" for latest one.   
That means, the latest one will be only allowed. So, in above case the latest one is POST call and that will override GET call. If you add same key("/comments") and try to call another http method say PUT below your code, then above two calls "GET" and "POST" are being overridden by this PUT call. 

So, handle your situation you need two have two different configuration of totoro. rain : 

app.use('/', totoro.rain({
    2: {
        "/comments": {
            method: "POST",
            endpointImplementation: test
        }
    }
}));

app.use('/', totoro.rain({
        "/comments": {
            method: "POST",
            endpointImplementation: test
        }
    }
}));

Then your code will run properly.

**Comment by VGJohn** [comment]
@douineauromain

Sorry about the late response! I've released a major update to support this case so you can now defined your endpoints in a list instead of a map. The ReadMe has been updated with an example. Some fields have been renamed to make lines shorter just so you know. Let me know if you have further problems.

Thanks for your feedback,
VGJohn
