### ISSUE TITLE
next parameter is not being passed by totoro.

### ISSUE THREAD

**Issue by mohsinAnomaly** [VGJohn/totoro#2]
router.post('/' + endpoint.apiVersion + endpoint.endpoint, urlencodedParser, function(req, res) {
                endpoint.endpointConfig.endpointImplementation(endpoint.apiVersion, req, res);
            });
In current implementation of totoro next function is not considered. If we add next parameter in endpointImplemenation(actual function) then it shows undefined. If we need to pass error to global error handler we need next in endpointImplementation. 
To handle this, we can change the code to 
router.post('/' + endpoint.apiVersion + endpoint.endpoint, urlencodedParser, function(req, res, next) {
                endpoint.endpointConfig.endpointImplementation(endpoint.apiVersion, req, res, next);
            });
That will help to call global error handler.

**Comment by VGJohn** [comment]
Hi @mohsinAnomaly,
I've release an update to include this parameter now. Let me know if you have any more issues. Thanks for the feedback.
Regards,
VGJohn
