### ISSUE TITLE
Call for maintainer (npmjs.org)

### ISSUE THREAD

**Issue by tusharpandey13** [VGJohn/totoro#9]
I've used this package before and I would like to become a maintainer for this project. I will ensure regular updates.

**Comment by VGJohn** [comment]
Hi @tusharpandey13, thanks for your interest! I've unfortunately not done much work with node for the past couple of years so it would be great to have a maintainer with more up-to-date experience. I sent you an invite, happy coding!

**Comment by tusharpandey13** [comment]
Thanks, @VGJohn, I'll see what I can do to keep it updated. :)

**Comment by tusharpandey13** [comment]
@VGJohn can you also add me on npm, so I can publish the changes?

**Comment by VGJohn** [comment]
No problem, you should be added as a maintainer on npm now as well

**Comment by tusharpandey13** [comment]
Thanks
